Charter/Controllers/ClientsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Charter.Data;
using Charter.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PayPal.Api;


namespace Charter.Controllers
{

    [Authorize(Roles = "Captain")]
    
    public class ClientsController : Controller
    {

        private ApplicationDbContext _context;

        public ClientsController(ApplicationDbContext context)
        {
            _context = context;
        }
        // GET: Clients
        public ActionResult Index()
        {
            try
            {

                var client = _context.clients.ToList();
                if (client == null)
                {
                    return RedirectToAction("CreateClient");
                }

                return View(client);
            }
            catch
            {
                return RedirectToAction("CreateClient");
            }
        }

        // GET: Clients/Details/5
        public ActionResult Details(int id)
        {
            var client = _context.clients.Where(h => h.ClientId == id).SingleOrDefault();
            return View(client);
        }

        public ActionResult CreateClient()
        {
            ClientsModel clientsModel = new ClientsModel();
           
            return View(clientsModel);
        }

        // POST: Captain/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateClient(ClientsModel clientsModel)
        {
            try
            {
                
                _context.clients.Add(clientsModel);
                _context.SaveChanges();

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        public async Task<IActionResult> EditClient(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var client = await _context.clients.FindAsync(id);
            if (client == null)
            {
                return NotFound();
            }

            return View(client);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditClient(int id, ClientsModel clientsModel)
        {
            if (id != clientsModel.ClientId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(clientsModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {

                }
                return RedirectToAction("Index");
            }

            // return View(captainsModel);
            return RedirectToAction("Index");
        }

        public ActionResult DeleteClient(int id)
        {
            var clientToDelete = _context.clients.Where(s => s.ClientId == id).FirstOrDefault();
            return View(clientToDelete);
        }

        // POST: Captain/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteClient(int id, ClientsModel clientsModel)
        {
            try
            {
                var clientToDelete = _context.clients.Find(id);
                _context.clients.Remove(clientToDelete);
                _context.SaveChanges();

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        

    }
}

Charter/Controllers/MessagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Charter.Data;
using Charter.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Charter.Controllers
{
    public class MessagesController : Controller
    {

        private ApplicationDbContext _context;

        public MessagesController(ApplicationDbContext context)
        {
            _context = context;
        }
        // GET: Messages
        public ActionResult Index()
        {
            var messageList = _context.messages.ToList();
            return View(messageList);
        }

       

        // GET: Messages/Create
        public ActionResult CreateMessage()
        {
            MessagesModel messagesModel = new MessagesModel();
            return View(messagesModel);
        }

        // POST: Messages/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateMessage(MessagesModel messagesModel)
        {
            try
            {
                _context.messages.Add(messagesModel);
                _context.SaveChanges();

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Charter/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Charter</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                @*<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Charter</a>*@
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark menu-text" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark menu-text" asp-area="" asp-controller="Messages" asp-action="CreateMessage">Leave Message</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark menu-text" asp-area="" asp-controller="Messages" asp-action="Index">View Messages</a>
                        </li>
                        @if (SignInManager.IsSignedIn(User) && User.IsInRole("Captain"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark menu-text" asp-area="" asp-controller="Clients" asp-action="CreateClient">Create Client</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark menu-text" asp-area="" asp-controller="Clients" asp-action="Index">Get Clients</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark menu-text" asp-area="" asp-controller="Home" asp-action="Privacy">Chat</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Charter - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>